spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: "jdbc:h2:mem:localDb;MODE=MSSQLServer"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    test-rollback-on-update: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

#Logging section settings
#levels are ordered as follows: TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    com:
      project:
        performance:
          PerformanceMonitorInterceptor: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO
    root: INFO
